### ISSUE TITLE
Features requiring direct linking to MIT Open 

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/ol-keycloak#47]
There are a few features we want that are ideal to have a per-environment reference to the MIT Open root url (i.e. `http://mitopen.odl.mit.edu/`) in situations where it needs to be a direct link regardless of the context. There's possibly a few ways to deal with this:

#### Approach

- Statically link to the production url in our templates. It might be confusing in non production environments, but we can note that as a known limitation
- Setting within Keycloak itself. I did some preliminary investigation for this and it is more involved and even more undocumented (to the degree of needed to dig through their source code). It's likely this is going to either take too long or dead end.
- Derive the value from an environment variable. This doesn't involve needing to acquire a technical understanding of Keycloak's internals, but it's a bit nonstandard for Keycloak itself which wants to have values like this stored in the DB. Probably going to go with this though.

#### Acceptance Criteria

- [ ] Logo should link to MIT Open (need to determine if this can be done on a per-environment basis or if it it'll have to be static).
- [ ] When the user logs in, if they don't have a destination we should direct them over to Open. This is acceptable as a link/button on whatever page they end up on, but we don't want it to be a dead end.

**Comment by pdpinch** [comment]
Is this still an issue?

**Comment by rhysyngsun** [comment]
It's solved for html pages but not for emails. It's probably not a dealbreaker though since emails just statically link to production and we can live with that so I'll close this for now.
