### ISSUE TITLE
Align Email templates to the mockups

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/ol-keycloak#48]
mockups:
[Email Verify](https://www.figma.com/proto/M7raxNajixAyAB2MNfAB6l/MIT-Canvas?type=design&node-id=456-11513&viewport=-781%2C-3934%2C0.55&t=7eELsYUBNVjkRlnI-0&scaling=min-zoom&starting-point-node-id=1101%3A962&show-proto-sidebar=1)
[Email Reset Password](https://www.figma.com/proto/M7raxNajixAyAB2MNfAB6l/MIT-Canvas?type=design&node-id=456-11513&viewport=-772%2C-3865%2C0.53&t=7eELsYUBNVjkRlnI-0&scaling=min-zoom&starting-point-node-id=1101%3A964&show-proto-sidebar=1)

(from https://github.com/mitodl/hq/issues/3473)

- [ ] New account email confirmation
- [ ] Password reset email
- [ ] General catch all template in case we missed anything?

**Comment by steven-hatch** [comment]
Designs for Email Template
[Email Verify](https://www.figma.com/proto/M7raxNajixAyAB2MNfAB6l/MIT-Canvas?type=design&node-id=456-11513&viewport=-781%2C-3934%2C0.55&t=7eELsYUBNVjkRlnI-0&scaling=min-zoom&starting-point-node-id=1101%3A962&show-proto-sidebar=1)
[Email Reset Password](https://www.figma.com/proto/M7raxNajixAyAB2MNfAB6l/MIT-Canvas?type=design&node-id=456-11513&viewport=-772%2C-3865%2C0.53&t=7eELsYUBNVjkRlnI-0&scaling=min-zoom&starting-point-node-id=1101%3A964&show-proto-sidebar=1)

**Please Note:** These designs DO NOT need to be pixel perfect and DO NOT need to use Neue Font. Please use a system font like Arial so its safe for all users getting these emails. Please let me know if you have any questions.
